# This is a generated file. Not intended for manual editing.
services:
  hm.presentation.webui:
    build:
      context: "C:\\Proiecte\\Hotel-Management\\HM\\Hotel Management App"
      dockerfile: "HM.Presentation.WebUI/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/JetBrains/RiderDebuggerTools/linux-x64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/JetBrains/RiderDebuggerTools/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57000"
    - "--backend-port=57200"
    - "--roslyn-worker-port=57429"
    - "--timeout=60"
    environment:
      ASPNETCORE_STATICWEBASSETS: "/app/bin/Debug/net9.0/HM.Presentation.WebUI.staticwebassets.runtime.CT.json"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/JetBrains/RiderDebuggerTools"
      RESHARPER_LOG_CONF: "/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    image: "hm.presentation.webui:dev"
    ports:
    - "127.0.0.1:57029:57000"
    - "127.0.0.1:57229:57200"
    - "127.0.0.1:57429:57429"
    volumes:
    - "C:\\Proiecte\\Hotel-Management\\HM\\Hotel Management App\\HM.Presentation.WebUI:/app:rw"
    - "C:\\Proiecte\\Hotel-Management\\HM\\Hotel Management App:/src:rw"
    - "C:\\Users\\andri\\AppData\\Roaming\\Microsoft\\UserSecrets:/home/app/.microsoft/usersecrets"
    - "C:\\Users\\andri\\.nuget\\packages:/home/app/.nuget/packages"
    - "C:\\Users\\andri\\AppData\\Local\\JetBrains\\RiderRemoteDebugger\\2025.3.1\\\
      Linux64:/opt/JetBrains/RiderDebuggerTools"
    - "C:\\Program Files\\JetBrains\\JetBrains Rider 2025.2.1\\bin\\backend-log.xml:/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    - "C:\\Users\\andri\\AppData\\Local\\JetBrains\\Rider2025.3\\log\\DebuggerWorker\\\
      JetBrains.Debugger.Worker.2026_2_04_18_35_56:/var/opt/JetBrains/RiderDebuggerTools:rw"
    working_dir: "/app"
