services:
  hm.presentation.webui:
    image: hm.presentation.webui
    build:
      context: .
      dockerfile: HM.Presentation.WebUI/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:8081;http://+:8080
      - ASPNETCORE_Kestrel__Certificates__Default__Password=123ABC
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/hotelcertification.pfx
    ports:
      - 5000:8080
      - 5001:8081
    volumes:
      - ${USERPROFILE:-$HOME}/.aspnet/https:/https:ro
    depends_on:
      sqlserver:
        condition: service_healthy
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2025-latest
    container_name: sqlserver_db
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Password123!
      - MSSQL_PID=Developer
    volumes:
      - sql_data:/var/opt/mssql
    ports:
      - 1433:1433
    healthcheck:
      test: [ "CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P 'Password123!' -C -Q 'SELECT 1' || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  sql_data: