name: Continuous Integration (CI) pipeline
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  Solution_Name: HM/Hotel Management App/Hotel Management App.sln
jobs:
  build-windows:
    strategy:
      matrix:
        configuration: [Debug, Release]
    runs-on: windows-latest
    steps:
    # 1. Checkout the code
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # 2. Setup Java
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: 'zulu'

    # 3. Cache SonarQube Cloud packages
    - name: Cache SonarQube Cloud packages
      uses: actions/cache@v4
      with:
        path: ~\sonar\cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar

    # 4. Cache SonarQube Cloud scanner
    - name: Cache SonarQube Cloud scanner
      id: cache-sonar-scanner
      uses: actions/cache@v4
      with:
        path: ${{ runner.temp }}\scanner
        key: ${{ runner.os }}-sonar-scanner
        restore-keys: ${{ runner.os }}-sonar-scanner

    # 5. Install SonarQube Cloud scanner
    - name: Install SonarQube Cloud scanner
      if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
      shell: powershell
      run: |
        New-Item -Path ${{ runner.temp }}\scanner -ItemType Directory
        dotnet tool update dotnet-sonarscanner --tool-path ${{ runner.temp }}\scanner

    # 6. Install .NET SDK
    - name: Install .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    # 7. Begin SonarQube Analysis
    - name: Begin SonarQube Analysis
      if: matrix.configuration == 'Release'
      shell: powershell
      run: |
        ${{ runner.temp }}\scanner\dotnet-sonarscanner begin /k:"Robert-Andries_Hotel-Management" /o:"robisca-1" /d:sonar.token="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.cs.opencover.reportsPaths="**/coverage.opencover.xml"

    # 8. Restore NuGet packages
    - name: Restore
      run: dotnet restore "${{ env.Solution_Name }}"

    # 9. Build the solution
    - name: Build
      run: dotnet build "${{ env.Solution_Name }}" --configuration ${{ matrix.configuration }} --no-restore
      env:
        Configuration: ${{ matrix.configuration }}

    # 10. Run tests with Coverage
    - name: Test
      run: dotnet test "${{ env.Solution_Name }}" --configuration ${{ matrix.configuration }} --no-build --collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=cobertura,opencover DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Exclude="[HM.Infrastructure]*,[HM.Presentation.*]*"
      env:
        Configuration: ${{ matrix.configuration }}

    # 11. End SonarQube Analysis
    - name: End SonarQube Analysis
      if: matrix.configuration == 'Release'
      shell: powershell
      run: |
        ${{ runner.temp }}\scanner\dotnet-sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"

    # 10. Install ReportGenerator
    - name: Install ReportGenerator
      run: dotnet tool install -g dotnet-reportgenerator-globaltool

    # 11. Merge Coverage Reports
    - name: Merge Coverage Reports
      run: reportgenerator -reports:"**/coverage.cobertura.xml" -targetdir:"coverage" -reporttypes:"Cobertura"

    # 12. Check Coverage Threshold
    - name: Check Coverage Threshold
      shell: pwsh
      run: |
        $xml = [xml](Get-Content coverage/Cobertura.xml)
        $lineRate = [double]$xml.coverage.'line-rate'
        $percent = $lineRate * 100
        Write-Host "Current Line Coverage: $($percent)%"
        if ($percent -lt 50) {
          Write-Error "Code coverage is below 50%!"
          exit 1
        }
  snyk-scan:
    runs-on: ubuntu-latest
    environment: SNYK_TOKENS
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Install .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore
      run: dotnet restore "${{ env.Solution_Name }}" /p:EnableWindowsTargeting=true
    - name: Snyk Security Scan
      uses: snyk/actions@0.4.0
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        command: test
        args: --file="${{ env.Solution_Name }}" --severity-threshold=medium
        json: true
