name: Continuous Integration (CI) pipeline
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  Solution_Name: HM/Hotel Management App/Hotel Management App.sln
jobs:
  build-windows:
    strategy:
      matrix:
        configuration: [Debug, Release]
    runs-on: windows-latest
    steps:
    # 1. Checkout the code
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    # 2. Install .NET SDK
    - name: Install .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    
    # 3. Restore NuGet packages
    - name: Restore
      run: dotnet restore "${{ env.Solution_Name }}"
    
    # 4. Build the solution
    - name: Build
      run: dotnet build "${{ env.Solution_Name }}" --configuration ${{ matrix.configuration }} --no-restore
      env:
        Configuration: ${{ matrix.configuration }}
    
    # 5. Run tests with Coverage
    - name: Test
      run: dotnet test "${{ env.Solution_Name }}" --configuration ${{ matrix.configuration }} --no-build --collect:"XPlat Code Coverage"
      env:
        Configuration: ${{ matrix.configuration }}
    # 6. Install ReportGenerator
    - name: Install ReportGenerator
      run: dotnet tool install -g dotnet-reportgenerator-globaltool
    # 7. Merge Coverage Reports
    - name: Merge Coverage Reports
      run: reportgenerator -reports:"**/coverage.cobertura.xml" -targetdir:"coverage" -reporttypes:"Cobertura"
    # 8. Check Coverage Threshold
    - name: Check Coverage Threshold
      shell: pwsh
      run: |
        $xml = [xml](Get-Content coverage/Cobertura.xml)
        $lineRate = [double]$xml.coverage.'line-rate'
        $percent = $lineRate * 100
        Write-Host "Current Line Coverage: $($percent)%"
        if ($percent -lt 60) {
          Write-Error "Code coverage is below 60%!"
          exit 1
        }
  snyk-scan:
    runs-on: ubuntu-latest
    environment: SNYK_TOKENS
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Install .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore
      run: dotnet restore "${{ env.Solution_Name }}" /p:EnableWindowsTargeting=true
    - name: Snyk Security Scan
      uses: snyk/actions@0.4.0
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      with:
        command: test
        args: --file="${{ env.Solution_Name }}" --severity-threshold=medium
        json: true
